version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: kubernetes/image/Dockerfile
    image: "alisonmukoma/revotask:latest"
    container_name: api
    restart: on-failure
    ports:
      - "8080:8000"
    volumes:
      - ./api/:/app/api/
 
  tests:
    build: 
      context: .
      dockerfile: kubernetes/image/Dockerfile
    image: "alisonmukoma/revotask:latest"
    command: "pytest api"
    container_name: tests
 