---
# Source: revotask/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: revotask
  labels:
    environment: prod
    app: revotask
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: revotask
    environment: prod
---
# Source: revotask/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: revotask
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revotask
      environment: prod
  template:
    metadata:
      name: revotask
      namespace: api
      labels:
        app: revotask
        environment: prod
    spec:
      containers:
        - name: api
          image: "alisonmukoma/revotask:latest"
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "220Mi"
              cpu: "15m"
            limits:
              memory: "512Mi"
              cpu: "20m"
